---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2021/3/5 15:42
--- 该文件只定义注解，实际并不加载和运行

---@class GUIWindowManager
---@field Instance fun() : GUIWindowManager
---@field CreateGUIWindow1 fun(self : GUIWindowManager, type : string, name : string) : CGUIWindow
---@field LoadWindowFromJSON fun(self : GUIWindowManager, name : string) : CGUIWindow
---@field CreateWindowFromTemplate fun(self : GUIWindowManager, name : string, jsonName : string) : CGUIWindow
---@field DestroyGUIWindow fun(self : GUIWindowManager, window : CGUIWindow) : void
GUIWindowManager = GUIWindowManager

---@alias CGUIWindow GUIActorWindow | GUIButton | GUICheckBox | GUIEditBox | GUIGridView | GUILayout | GUIListBox | GUIProgressBar | GUIRadioButton | GUIStaticImage | GUIStaticText | GUIPageView | GUIListHorizontalBox | GUIWindow

---@class GameSettings
---@field setLockViewPos fun(self : GameSettings, lock : boolean) : void
---@field setCurQualityLevel fun(self : GameSettings, level : number) : void
---@field getCurQualityLevel fun(self : GameSettings) : number

---@class Blockman
---@field Instance fun() : Blockman
---@field viewerRenderPos fun(self : Blockman) : Vector3
---@field viewerRenderYaw fun(self : Blockman) : number
---@field viewerRenderPitch fun(self : Blockman) : number
---@field viewerRenderDistance fun(self : Blockman) : number
---@field getViewerPitch fun(self : Blockman) : number
---@field getViewerYaw fun(self : Blockman) : number
---@field getViewerPos fun(self : Blockman) : Vector3
---@field getClientHttpHost fun(self : Blockman) : string
---@field setPersonView fun(self : Blockman, view : number) : void
---@field changeCameraView fun(self : Blockman, pos : Vector3, yaw : number, pitch : number, distance : number, smooth : number) : void
---@field setKeyPressing fun(self : Blockman, key : string, value : boolean) : void
---@field getGameFPS fun(self : Blockman) : number
---@field gameSettings GameSettings
Blockman = Blockman

---@class CGame
---@field Instance fun() : CGame
---@field getPlatformUserId fun(self : CGame) : number
---@field isDebuging fun(self : CGame) : boolean
---@field setUserInfo fun(self : CGame, userToken : string, baseUrl : string, inviter : number) : void
CGame = CGame

---@class GUISystem
---@field Instance fun() : GUISystem
---@field GetRootWindow fun(self : GUISystem) : GUIWindow
---@field GetScreenWidth fun(self : GUISystem) : number
---@field GetScreenHeight fun(self : GUISystem) : number
GUISystem = GUISystem

---@class TextureAtlasRegister
---@field Instance fun() : TextureAtlasRegister
---@field addMemTextureAtlas fun(self : TextureAtlasRegister, texture : string, path : string) : void
TextureAtlasRegister = TextureAtlasRegister

---@class SoundSystem
---@field Instance fun() : SoundSystem
---@field playEffectByType fun(self : SoundSystem, soundId : number) : void
SoundSystem = SoundSystem

---@class WorldImage
---@field position Vector3
---@field scale number
---@field duration number

---@class WorldImageRender
---@field Instance fun() : WorldImageRender
---@field addWorldImage fun(self : WorldImageRender, images : table, pos : Vector3, scale : number, duration : number) : WorldImage
WorldImageRender = WorldImageRender

---@class WallTextRenderer
---@field Instance fun() : WallTextRenderer
---@field addWallText fun(self : WallTextRenderer, txt : string, pos : Vector3, pitch : number, yaw : number, limitMinSize : number, duration : number, scale : number, font : string, lineHeight : number) : void
WallTextRenderer = WallTextRenderer

---@class EffectSystem
---@field getEffectTimeLength fun(self : EffectSystem) : number
---@field setScaleTime fun(self : EffectSystem, scaleTime : number) : void
---@field getScaleTime fun(self : EffectSystem) : number

---@class SimpleEffect
---@field mEffectName string
---@field mTemplateName string
---@field mPosition Vector3
---@field mDuration number
---@field mEffect EffectSystem
---@field setScale fun(self : SimpleEffect, scale : Vector3) : void
---@field rotate fun(self : SimpleEffect, pitch : number, yaw : number, roll : number) : void

---@class WorldEffectManager
---@field Instance fun() : WorldEffectManager
---@field addSimpleEffect fun(self : WorldEffectManager, effectName : string, pos : Vector3, pitch : number, yaw : number, roll : number, duration : number, scale : Vector3, extendName : string, isSpecialRender : boolean) : SimpleEffect
---@field addSimpleEffect1 fun(self : WorldEffectManager, effectName : string, pos : Vector3, yaw : number, duration : number, scale : Vector3, extendName : string, isSpecialRender : boolean) : SimpleEffect
---@field getSimpleEffect fun(self : WorldEffectManager, effectName : string, pos : Vector3, extendName : string) : SimpleEffect
---@field destoryAllSimpleEffect fun(self : WorldEffectManager) : void
WorldEffectManager = WorldEffectManager

---@class GlobalProperty
---@field Instance fun() : GlobalProperty
---@field setBoolProperty fun(self : GlobalProperty, key : string, value : boolean) : void
---@field getBoolProperty fun(self : GlobalProperty, key : string) : boolean
---@field setIntProperty fun(self : GlobalProperty, key : string, value : number) : void
---@field getIntProperty fun(self : GlobalProperty, key : string) : number
---@field setFloatProperty fun(self : GlobalProperty, key : string, value : number) : void
---@field getFloatProperty fun(self : GlobalProperty, key : string) : number
---@field setStringProperty fun(self : GlobalProperty, key : string, value : string) : void
---@field getStringProperty fun(self : GlobalProperty, key : string) : string
GlobalProperty = GlobalProperty

---@class CameraManager
---@field Instance fun() : CameraManager
---@field getMainCamera fun(self : CameraManager) : Camera
---@field createCamera fun(self : CameraManager, name : string, mode : number, isFixedYaw : boolean) : Camera
---@field findCamera fun(self : CameraManager, name : string) : Camera
CameraManager = CameraManager

---@class Camera
---@field getActiveCamera fun() : Camera
---@field setPosition fun(self : Camera, pos : Vector3) : void
---@field setTarget fun(self : Camera, target : Vector3) : void
---@field setDirection fun(self : Camera, dir : Vector3) : void
---@field setUp fun(self : Camera, up : Vector3) : void
---@field yaw fun(self : Camera, yaw : number) : void
---@field pitch fun(self : Camera, pitch : number) : void
---@field roll fun(self : Camera, roll : number) : void
---@field rotate fun(self : Camera, vAxis : Vector3, rad : number) : void
---@field move fun(self : Camera, offset : Vector3) : void
---@field getPosition fun(self : Camera) : Vector3
---@field getDirection fun(self : Camera) : Vector3
---@field update fun(self : Camera) : void
---@field setProjectionMode fun(self : Camera, mode : number) : void
---@field getName fun(self : Camera) : string
---@field getFov fun(self : Camera) : number
---@field setFov fun(self : Camera, fov: number) : void
---@field setFov2 fun(self : Camera, fov: number) : void
Camera = Camera

---@class PlatformUtil
---@field isPlatformWindows fun() : boolean
---@field getLordPlatform fun() : number
PlatformUtil = PlatformUtil

---@class ActorObject

---@class EffectNode : MovableNode
---@field Load fun(cfg : table) : EffectNode
---@field start fun(self : EffectNode)
---@field destroy fun(self : EffectNode)
---@field setWorldPosition fun(self : EffectNode, position : Vector3)
EffectNode = EffectNode

---@class TdAudioEngine
---@field Instance fun() : TdAudioEngine
---@field play2dSound  fun(self : TdAudioEngine, path : string, isLoop : boolean) : number --return sound id
---@field play3dSound  fun(self : TdAudioEngine, path : string, position : Vector3, isLoop : boolean) : number --return sound id
---@field stopSound fun(self : TdAudioEngine, id : number)
---@field pauseSound fun(self : TdAudioEngine, id : number)
---@field resumeSound fun(self : TdAudioEngine, id : number)
---@field isPlaying fun(self : TdAudioEngine, id : number)
---@field setGlobalVolume fun(self : TdAudioEngine, volume : number)
---@field setSoundsVolume fun(self : TdAudioEngine, id : number, volume : number)
TdAudioEngine = TdAudioEngine