---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luo.
--- DateTime: 2020/3/10 17:27
---

function FunctionSetting:init()
    local path = Root.Instance():getRootPath() .. "Media/functionSetting.json"
    self.config = {}
    local file = io.open(path)
    if not file then
        return {}
    end
    file:close()
    self.config = Lib.read_json_file(path) or {}
end

function FunctionSetting:disableFriend()
    return self.config.friend or false
end

function FunctionSetting:disableRecharge()
    if CGame.instance:getIsMobileEditor() then
        return true
    end
    return self.config.recharge or false
end

return FunctionSetting