---
--- Generated by PluginCreator
--- report mainLua
--- DateTime:2021-06-16
---

require "common.config.report_config"
require "common.player_report"
require "common.entity_report"

if World.isGameServer then
    require "server.gm_report"
end

local ReportConfig = T(Config, "ReportConfig")
local ReportAttr = T(Config, "ReportAttr")

local handlers = {}

if World.isClient then
    Lib.subscribeEvent(Event.EVENT_OPEN_WINDOW, function(uiName)
        if World.cfg.reportSetting and World.cfg.reportSetting.uiOpen and World.cfg.reportSetting.uiOpen[uiName] then
            handlers.report("uiOpen", {name=uiName})
        end
    end)

    Lib.subscribeEvent(Event.EVENT_CLOSE_WINDOW, function(uiName)
        if World.cfg.reportSetting and World.cfg.reportSetting.uiClose and World.cfg.reportSetting.uiClose[uiName] then
            local wnd = UI:getWnd(uiName, true)
            local uiTime = wnd and wnd:root():getTotalOpenTime() or 0
            handlers.report("uiClose", {name=uiName, time=uiTime})
        end
    end)
else
end

--记录登录时间，上报可以加在线时长
function handlers.ENTITY_ENTER(context)
    if World.cfg.reportSetting and World.cfg.reportSetting.disableReportEvent
            and World.cfg.reportSetting.disableReportEvent["player_in"] then
        return
    end
    local entity = context.obj1
    if not (entity and entity:isValid()) then
        return
    end
    if entity.isPlayer then
        entity:updateLoginTs()
        handlers.report("player_in", nil, entity)
    else
    end
end

function handlers.ENTITY_LEAVE(context)
    if World.cfg.reportSetting and World.cfg.reportSetting.disableReportEvent
            and World.cfg.reportSetting.disableReportEvent["player_out"] then
        return
    end
    local entity = context.obj1
    if not (entity and entity:isValid()) then
        return
    end
    if entity.isPlayer then
        handlers.report("player_out", nil, entity)
    end
end

function handlers.ADD_CURRENCY(context)
    if World.cfg.reportSetting and World.cfg.reportSetting.disableReportEvent
            and World.cfg.reportSetting.disableReportEvent["add_currency"] then
        return
    end
    local reportData = {
        money_type = context.coinName,
        count = context.coincount,
        string_reason = context.reason
    }
    handlers.report("add_currency", reportData, context.obj1)
end

function handlers.report(type, defaultData, player)
    GameReport:report(type, defaultData, player)
end

function handlers.reportDataByUserId(type, data, userId)
    GameReport:reportByUserId(type, data, userId)
end

return function(name, ...)
	if type(handlers[name]) ~= "function" then
		return
	end
	return handlers[name](...)
end
