---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/23 15:19
---
local CommonActivity = T(Lib, "CommonActivity") ---@type CommonActivity
local BlindBoxActivity = T(Lib, "BlindBoxActivity") ---@type BlindBoxActivity
local handles = T(Player, "PackageHandlers")

function handles:MustLotteryDelete(packet)
    CommonActivity:onMustLotteryDelete(self, packet.data)
end

function handles:MustLotteryDoLottery(packet)
    CommonActivity:onMustLotteryDoLottery(self, packet.data)
end

function handles:LuckyLottery(packet)
    CommonActivity:onLuckyLottery(self, packet.data)
end

function handles:CommonActivityOpenChest(packet)
    CommonActivity:onOpenChest(self, packet.data)
end

function handles:BlindBoxOpen(packet)
    BlindBoxActivity:onBlindBoxOpen(self, packet.data)
end