---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cs.
--- DateTime: 2019/4/9 11:05
---
---
local ShopBase = Shop.GetType("Base")
local MoneyShop = Shop.GetType("MoneyShop")

local setting = require "common.setting"

function MoneyShop:canBuy(packet, from)
    print("money shop can buy")
    if not ShopBase.canBuy(self, packet, from) then
        return false
    end
    return true
end

local function normalReward(packet, from)
    --auth存库
    local cfg = Shop.Cfg(packet.name, from)
    from:reward(cfg.rewardParams, packet.sourceId)
    ShopBase.successNotice(cfg, packet, from)
end

function MoneyShop:buy(packet, from)
    if not ShopBase.doPay(self, packet, from, normalReward) then
        return false
    end
    return true
end
