---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/6/28 16:02
---
local reportController = require "common.report.controller"

function reportController:requestEventTrackingList()
    if not Me then
        return
    end
    Me:sendPacket({ pid = "RequestEventTrackingList" })
end

return reportController