---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/23 15:54
---
---@class CommonActivityType
local CommonActivityType = T(Config, "CommonActivityType")
CommonActivityType.MustLottery = 1
CommonActivityType.LuckyLottery = 2

---@class CommonActivity
local CommonActivity = T(Lib, "CommonActivity")
---@class BlindBoxActivity
local BlindBoxActivity = T(Lib, "BlindBoxActivity")

require "common.activity_event"
require "common.activity_lib"
require "player.player_activity"

require "logic.common_activity"
require "logic.blindbox_activity"

local handlers = {}

function handlers.onGameReady()
    require "common.config.common_activity_chest_config"
    require "common.config.common_activity_config"
    require "common.config.common_activity_reward_config"
    require "common.config.lucky_lottery_price_config"
    require "common.config.lucky_value_config"
    require "common.config.must_lottery_price_config"
    require "common.config.blind_box_config"
    require "common.config.blind_box_reward_config"
end

function handlers.onPlayerReady(player)
    CommonActivity:onPlayerReady(player)
    BlindBoxActivity:onPlayerReady(player)
end

return function(name, ...)
    if type(handlers[name]) ~= "function" then
        return
    end
    handlers[name](...)
end