---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/23 16:01
---
local widget_base = require "ui.widget.widget_base"
local M = Lib.derive(widget_base)

function M:init(name)
    widget_base.init(self, name)
    self:initWnd()
end

function M:initWnd()
    self.ivSelected = self:child("CommonActivityTab-Selected")
    self.ivSelected:SetVisible(false)
    self.ivRedPoint = self:child("CommonActivityTab-Red-Point")
    self.ivRedPoint:SetVisible(false)
    self.ivText = self:child("CommonActivityTab-Text")
    self.btnClick = self:child("CommonActivityTab-Click")
    self:subscribe(self.btnClick, UIEvent.EventButtonClick, function ()
        UI:getWnd("commonActivityLayout"):showActivity(self.activityId)
    end)
end

function M:onDataChanged(activity)
    self.activityId = activity.id
    self.ivText:SetText(Lang:getMessage(activity.tabLang))
end

function M:setSelected(selected)
    self.ivSelected:SetVisible(selected)
    if selected then
        self:setRedPoint(false)
    end
    self.btnClick:SetTouchable(not selected)
end

function M:isSelected()
    return self.ivSelected:IsVisible()
end

function M:setRedPoint(isShowRed)
    self.ivRedPoint:SetVisible(isShowRed)
    UI:getWnd("commonActivityMain"):checkTabsRedPoint()
end

function M:isHaveRedPoint()
    return self.ivRedPoint:IsVisible()
end

return M