---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/18 10:21
---
local LuaTimer = T(Lib, "LuaTimer") ---@type LuaTimer
local widget_base = require "ui.widget.widget_base"
local M = Lib.derive(widget_base)

function M:init()
    widget_base.init(self, "BlindBoxRewardGroup.json")
    self.items = {}
    self:initWnd()
end

function M:initWnd()
    self.tvHint = self:child("BlindBoxRewardGroup-Hint")
    self.llRewards = self:child("BlindBoxRewardGroup-Rewards")
end

function M:onDataChanged(data, delay)
    delay = delay or 0
    self.tvHint:SetText(Lang:getMessage(data.hint))
    local curXPos = 0
    self:addTimer(LuaTimer:schedule(function()
        for pos, reward in pairs(data.rewardGroup) do
            local xPos = curXPos
            self:addTimer(LuaTimer:schedule(function()
                local rewardItem = UIMgr:new_widget("commonActivityRewardItem",UI:getWnd("blindBoxRewardList"))
                rewardItem:invoke("setRewardData", reward.reward, true)
                rewardItem:SetArea({ 0, xPos }, { 0, 0 }, { 0, 68 }, { 0, 68 })
                rewardItem:invoke("SetEffectMask", "set:common_christmas_icon.json image:img_9_mask_chrismas")
                table.insert(self.items, rewardItem)
                self.llRewards:AddChildWindow(rewardItem:invoke("get"):root())
            end, (pos - 1) * 50))
            curXPos = curXPos + 80
        end
    end, delay))
end

function M:onDestroy()
    self.items = {}
end

return M