---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/13 10:19
---
local stack = class("stack") ---@class stack : cls

function stack:ctor(tb)
    self._data = tb or {} ---@type any[]
end

function stack:top()
    return self._data[-1]
end

function stack:top_pop()
    local ret = self:top()
    self:pop()
    return ret
end

function stack:empty()
    return self:size() == 0
end

function stack:size()
    return #self._data
end

function stack:push(value, pos)
    if pos then
        table.insert(self._data, pos, value)
    else
        table.insert(self._data, value)
    end
end

function stack:pop()
    table.remove(self._data)
end

return stack