---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by work.
--- DateTime: 2020/1/3 17:15
---
function M:init()
    WinBase.init(self, "hoverText.json")
    self.baseText = self:root()

end

function M:onOpen(arg)
    if not next(arg) then
        return
    end
    if arg.scale then
        self.baseText:SetTextScale(arg.scale)
    end
    if arg.text then
        local textArg = arg.textArg or {}
        table.insert(textArg, 1, arg.text)
        self.baseText:SetText(Lang:toText(textArg))
    end
    if type(arg.boaderColor)=="table" then
        self.baseText:SetTextBoader(arg.boaderColor)
    end
    if type(arg.width)=="table" then
        self.baseText:SetWidth(arg.width)
    end
end

return M