---
--- Generated by PluginCreator
--- easter_eggs gm
--- DateTime:2022-03-15
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

---@type EasterEggsRefreshPosConfig
local EasterEggsRefreshPosConfig = T(Config, "EasterEggsRefreshPosConfig")

local curIndex = 0
GMItem["easter_eggs/去下一个彩蛋"] = function(self)
    local playerState = self:getEasterEggState()

    curIndex = curIndex + 1

    for bitchIndex, config in pairs(playerState) do
        for mapType, list in pairs(config.posList) do
            local posConfig = list[curIndex]
            if not posConfig then
                curIndex = 1
                posConfig = list[1]
            end
            local id = posConfig.id

            local cfg = EasterEggsRefreshPosConfig:getCfgById(id)
            local pos = Lib.v3(cfg.pos[1],cfg.pos[2],cfg.pos[3])

            self:setMapPos(cfg.name, pos)
            return
        end
    end
end

local curIndex = 0
GMItem["easter_eggs/去下一个刷新点"] = function(self)
    local mapName = self.map.name

    local list = EasterEggsRefreshPosConfig:getAllConfigList()
    for id, config in ipairs(list) do
        if id > curIndex then
            curIndex = id

            local pos = Lib.v3(config.pos[1],config.pos[2],config.pos[3])
            self:setMapPos(config.map, pos)
            return
        end
    end

    curIndex = 0
    for id, config in ipairs(list) do
        if id > curIndex then
            curIndex = id

            local pos = Lib.v3(config.pos[1],config.pos[2],config.pos[3])
            self:setMapPos(config.map, pos)
            return
        end
    end
end

local mapCurIndex = 0
GMItem["easter_eggs/本地图Next刷新点"] = function(self)
    local mapName = self.map.name

    local list = EasterEggsRefreshPosConfig:getAllConfigList()
    for id, config in ipairs(list) do
        if id > mapCurIndex and config.map == mapName then
            mapCurIndex = id

            local pos = Lib.v3(config.pos[1],config.pos[2],config.pos[3])
            self:setMapPos(self.map, pos)
            return
        end
    end

    mapCurIndex = 0
    for id, config in ipairs(list) do
        if id > mapCurIndex and config.map == mapName then
            mapCurIndex = id

            local pos = Lib.v3(config.pos[1],config.pos[2],config.pos[3])
            self:setMapPos(self.map, pos)
            return
        end
    end
end