---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hlm.
--- DateTime: 2020/8/27 20:20
--- 用于管理一些UI的通用功能，适配等
---
---

local UIShowManage = T(UIMgr, "UIShowManage")

-- 原始屏幕大小
local screenWidth = 1280
local screenHeight = 720

-- UIMgr.UIShowManage:adapterFixedSize
function UIShowManage:init()
    self._desktop = GUISystem.instance:GetRootWindow()
    self.ratioX = self._desktop:GetPixelSize().x / screenWidth
    self.ratioY = self._desktop:GetPixelSize().y / screenHeight
end

function UIShowManage:getRatioX()
    return self.ratioX
end

function UIShowManage:getRatioX()
    return self.ratioY
end

function UIShowManage:getAdapterRatio()
    local ratioX = self.ratioX
    local ratioY = self.ratioY

    local ratio = (ratioX < ratioY) and ratioX or ratioY
    return ratio
end

-- 对特定UI整体适配调整, 引擎的适配是宽高各自拉伸
function UIShowManage:adapterFullSreenSize(childNode, initialWidth, initialHeight)
    local ratioX = self.ratioX
    local ratioY = self.ratioY
    -- 以比例小的为准
    local ratio = (ratioX < ratioY) and ratioX or ratioY
    childNode:SetWidth({0, initialWidth*ratio})
    childNode:SetHeight({0, initialHeight*ratio})
end

-- 小控件大屏的使用原来的大小，小屏的缩放
function UIShowManage:adapterFixedSize(childNode, initialWidth, initialHeight)
    local ratioX = self.ratioX
    local ratioY = self.ratioY

    local ratio = (ratioX < ratioY) and ratioX or ratioY
    if ratioX > 1 or ratioX > 1 then
        ratio = 1
    end
    childNode:SetWidth({0, initialWidth*ratio})
    childNode:SetHeight({0, initialHeight*ratio})
end

-- 小控件大屏的使用原来的大小，小屏的缩放，位置也一样
function UIShowManage:adapterAreaSize(childNode, initialX, initialY, initialWidth, initialHeight)
    local ratioX = self.ratioX
    local ratioY = self.ratioY

    local ratio = (ratioX < ratioY) and ratioX or ratioY
    if ratioX > 1 or ratioX > 1 then
        ratio = 1
    end
    childNode:SetArea({ 0, initialX*ratio }, { 0, initialY*ratio }, { 0, initialWidth*ratio }, { 0, initialHeight*ratio })
end
