---
--- Generated by PluginCreator
--- easter_eggs entity
--- DateTime:2022-03-15
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
