---
--- Generated by PluginCreator
--- easter_eggs player
--- DateTime:2022-03-15
---

local Player = Player
--function Player:xxxxx()
--end

function Player:checkEasterEggsIsReceive(id)
    local state = self:getEasterEggState()

    for index, posL in pairs(state) do
        if posL.receiveIndex[id] then
            return true
        end
    end

    return false
end