---
--- Generated by PluginCreator
--- DateTime:2022-03-15
---

if World.isClient then
    Event.EVENT_NEW_VIDEO_EFFECT_ITEM = Event.register("EVENT_NEW_VIDEO_EFFECT_ITEM")
    Event.EVENT_UPDATE_VIDEO_RECORD_STATE = Event.register("EVENT_UPDATE_VIDEO_RECORD_STATE")
else

end
