---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hlm.
--- DateTime: 2022/5/10 17:49
---

-- 录像录制状态
Define.newVideoRecordState = {
    NoneRecord = 0,        --未录制（录制结束）
    WaitStart = 1,      --等待开始录制倒计时
    WaitConfirm = 2,      --等待确认录制（取消录制）
    Recording = 3,      --正在录制
}