---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/6 10:15
---
require("data.dba"):init()

local dataService = {}

local globalDataStore = require "data.global_data_store"
function dataService:GetGlobalDataStore(space)
    return globalDataStore(space)
end

local rankDataStore = require "data.rank_data_store"
function dataService:GetRankDataStore(space)
    return rankDataStore(space)
end

local engineModule = require "common.engine_module"
engineModule.insertModule("DataService", dataService)