---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/6 10:21
---
local dba = require "data.dba"

local globalDataStore = {}

function globalDataStore:init(space)
    self._space = space
end

function globalDataStore:SetData(key, data)
    dba:setData(self._space, key, data)
end

function globalDataStore:RequestData(key, callback)
    dba:getData(self._space, key, callback)
end

function globalDataStore:RemoveData(key)
    dba:removeData(self._space, key)
end

function globalDataStore:UpdateData(key, callback)
    self:RequestData(key, function(data)
        local ret = callback(data)
        if ret ~= nil then
            self:SetData(key, ret)
        end
    end)
end

return function(space)
    if type(space) ~= "string" then
        Lib.logError("space type does not match!")
        return
    end
    local derive = Lib.derive(globalDataStore)
    derive:init(space)
    return derive
end