---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/23 15:50
---
function M:init()
    WinBase.init(self, "CommonActivityTextDialog.json")
    self:initWnd()
end

function M:initWnd()
    self.tvTitle = self:child("CommonActivityTextDialog-Title")
    self.tvText = self:child("CommonActivityTextDialog-Text")
    local btnClose = self:child("CommonActivityTextDialog-Close")
    self:subscribe(btnClose, UIEvent.EventWindowClick, function()
        UI:closeWnd("commonActivityTextDialog")
    end)
    local btnBackClose = self:child("CommonActivityTextDialog-Back-Close")
    self:subscribe(btnBackClose, UIEvent.EventButtonClick, function()
        UI:closeWnd("commonActivityTextDialog")
    end)
end

function M:showText(title, text)
    self.tvTitle:SetText(Lang:getMessage(title))
    self.tvText:SetText(Lang:getMessage(text))
    UI:openWnd("commonActivityTextDialog")
end

function M:isShowAnim()
    return true
end