---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 11:09
---

function M:init()
    WinBase.init(self, "BlindBoxMain.json")
    self:initWnd()
    self:initEvent()
end

function M:initWnd()
    self.btnEnterButton = self:child("BlindBoxMain-Enter-Button")
    self.ivEnterEffect = self:child("BlindBoxMain-Enter-Effect")
    self.ivRedPoint = self:child("BlindBoxMain-Red-Point")
    self.ivRedPoint:SetVisible(false)
end

function M:initEvent()
    self:subscribe(self.btnEnterButton, UIEvent.EventButtonClick, function()
        UI:openWnd("blindBoxLayout")
    end)
end
