---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2022/3/18 21:28
---
local class = require "common.3rd.middleclass.middleclass"
local singleton = require "common.3rd.middleclass.singleton"
local stateful = require "common.3rd.stateful.stateful"

---@type ConfigManager
local ConfigManager = class('ConfigManager')
ConfigManager:include(singleton)
T(MobileEditor, "ConfigManager", ConfigManager)

---@type CommandManager
local CommandManager = class('CommandManager')
CommandManager:include(singleton)
T(MobileEditor, "CommandManager", CommandManager)

---@type UIManager
local UIManager = class('UIManager')
UIManager:include(singleton)
T(MobileEditor, "UIManager", UIManager)

---@type InputManager
local InputManager = class('InputManager')
InputManager:include(singleton)
T(MobileEditor, "InputManager", InputManager)

---@type GizmoManager
local GizmoManager = class('GizmoManager')
GizmoManager:include(singleton)
T(MobileEditor, "GizmoManager", GizmoManager)

---@type MobileEditorCameraManager
local CameraManager = class('CameraManager')
CameraManager:include(singleton)
CameraManager:include(stateful)
T(MobileEditor, "CameraManager", CameraManager)

---@type TargetManager
local TargetManager = class('TargetManager')
TargetManager:include(singleton)
T(MobileEditor, "TargetManager", TargetManager)

---@type DataManager
local DataManager = class('DataManager')
DataManager:include(singleton)
T(MobileEditor, "DataManager", DataManager)

---@type SoundManager
local SoundManager = class('SoundManager')
SoundManager:include(singleton)
T(MobileEditor, "SoundManager", SoundManager)

---@type SkyboxManager
local SkyboxManager = class('SkyboxManager')
SkyboxManager:include(singleton)
T(MobileEditor, "SkyboxManager", SkyboxManager)

---@type LightManager
local LightManager = class('LightManager')
LightManager:include(singleton)
T(MobileEditor, "LightManager", LightManager)

---@type WeatherManager
local WeatherManager = class('WeatherManager')
WeatherManager:include(singleton)
T(MobileEditor, "WeatherManager", WeatherManager)

---@type GroundManager
local GroundManager = class('GroundManager')
GroundManager:include(singleton)
T(MobileEditor, "GroundManager", GroundManager)

---@type GameManager
local GameManager = class('GameManager')
GameManager:include(singleton)
GameManager:include(stateful)
T(MobileEditor, "GameManager", GameManager)

require "common.manager.config_manager"
require "common.manager.command_manager"
require "common.manager.ui_manager"
require "common.manager.input_manager"
require "common.manager.gizmo_manager"
require "common.manager.camera_manager"
require "common.manager.target_manager"
require "common.manager.data_manager"
require "common.manager.sound_manager"
require "common.manager.skybox_manager"
require "common.manager.light_manager"
require "common.manager.weather_manager"
require "common.manager.ground_manager"
require "common.manager.game_manager"