---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/5/27 17:16
---
---@class UISubAnimationImgMask : UISubAnimation
local UISubAnimationImgMask = Lib.class("UISubAnimationImgMask", require "ui.ui_animation.ui_subAnimation")

function UISubAnimationImgMask:onPlay()
    self.maskStart = tonumber(self.config.maskStart)
    self.maskEnd = tonumber(self.config.maskEnd)
    self.mask = self.maskStart
    self.maskDelta = (self.maskEnd - self.maskStart) / self.ticks
end

function UISubAnimationImgMask:onUpdate()
    if self.tick == self.ticks then
        self.mask = self.maskEnd
    else
        self.mask = self.mask + self.maskDelta
    end

    local radiusRaito = self.param and self.param.radiusRatio or 0.5
    local alpha = self.param and self.param.alpha or 0.5
    self.setMask = self.window:setMask(self.mask,radiusRaito,alpha)

    --Lib.logDebug("UISubAnimationTextAlpha:onUpdate ", self.alpha)
end

function UISubAnimationImgMask:onDestroy()
    --TODO
    if self.setMask then
        self.window:RemoveChildWindow1(self.setMask)
        GUIWindowManager.instance:DestroyGUIWindow(self.setMask)
    end
end

return UISubAnimationImgMask