---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/6/11 15:22
---
---@class UISubAnimationBackgroundColor : UISubAnimation
local UISubAnimationBackgroundColor = Lib.class("UISubAnimationBackgroundColor", require "ui.ui_animation.ui_subAnimation")

function UISubAnimationBackgroundColor:onPlay()
    self.valueStart = Lib.strToV4(self.config.valueStart)
    self.valueEnd = Lib.strToV4(self.config.valueEnd)
    self.value = self.valueStart
    self.valueDelta = (self.valueEnd - self.valueStart) / self.ticks
end

function UISubAnimationBackgroundColor:onUpdate()
    if self.tick == self.ticks then
        self.value = self.valueEnd
    else
        self.value = self.value + self.valueDelta
    end

    self.window:SetBackgroundColor({ self.value.x, self.value.y, self.value.z, self.value.w })
end

function UISubAnimationBackgroundColor:onDestroy()
    --TODO
end

return UISubAnimationBackgroundColor