---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/7/20 14:19
--- 集换系统工具类
---
local oldOnReceiveCommonRewardFunc = Player.onReceiveCommonReward

local function consumeExchangeProps(player, item)
    local params = Lib.splitString(item.gamePropsId, ":")
    if #params ~= 2 then
        return
    end
    local time = os.time()
    local propsType = params[1]
    local propsId = params[2]
    if item.expire == 0 then
        player["onReceiveCommonReward"](player, propsType, propsId, item.propsAmount, 0)
    else
        if item.expire - time > 0 then
            player["onReceiveCommonReward"](player, propsType, propsId, item.propsAmount, item.expire - time)
        end
    end
end

---领取集换特权道具
local function receiveExchangeProps(player)
    local func = player["onReceiveCommonReward"]
    if func == oldOnReceiveCommonRewardFunc then
        ---没有重写集换式领取奖励方法
        return
    end
    if type(func) ~= "function" then
        return
    end
    local userId = player.platformUserId
    AsyncProcess.GetExchangeProp(userId, function(data)
        local player1 = Game.GetPlayerByUserId(userId)
        if not player1 then
            return
        end
        local propsIds = {}
        for _, item in pairs(data) do
            if item.expire == nil or item.expire == "" then
                item.expire = "0"
            end
            if item.propsAmount == nil or item.propsAmount == "" then
                item.propsAmount = "1"
            end
            item.expire = math.floor(tonumber(item.expire))
            item.propsAmount = tonumber(item.propsAmount)
            propsIds[item.gamePropsId] = true
        end
        for propsId, _ in pairs(propsIds) do
            AsyncProcess.ConsumeExchangeProp(userId, propsId, function()
                local player2 = Game.GetPlayerByUserId(userId)
                if not player2 then
                    return
                end
                for _, item in pairs(data) do
                    if item.gamePropsId == propsId then
                        consumeExchangeProps(player2, item)
                    end
                end
            end)
        end
    end)
end

function Game.tryPlayerGetExchangeProps(player)
    receiveExchangeProps(player)
end