---
--- Generated by PluginCreator
--- easter_eggs entity_common
--- DateTime:2022-03-15
---

local ValueDef = T(Entity, "ValueDef")
-- key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
ValueDef.easterEggState 		= {false,   false,  true,   false, { },                      true}
local Entity = Entity

function Entity:setEasterEggState(data)
    self:setValue("easterEggState", data)
end

function Entity:getEasterEggState()
    return self:getValue("easterEggState") or { }
end