---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/6/28 16:18
---
local ReportAgent = {}

local ReportController = require "report.controller"

local function validPlayer(player)
    if not player or not player.isPlayer then
        Lib.log("The player reported by the game data does not exist", 3)
        return false
    end
    return true
end

function ReportAgent:reportData(eventName, eventMap, player)
    if not validPlayer(player) then
        return false
    end
    ReportController:tryRequestList()
    if not ReportController:checkValidEventName(eventMap.event_name) then
        return false
    end
    local userId = player.platformUserId
    if ReportController:checkExceedFrequency(userId) then
        return false
    end
    ReportController:signFrequency(userId)
    GameAnalytics.NewDesign(userId, eventName, eventMap)
    return true
end

return ReportAgent