
if World.isClient then
    Event.EVENT_SOUND_MOON_CHANGE  = Event.register("EVENT_SOUND_MOON_CHANGE")
    Event.EVENT_SOUND_TIME_CHANGE  = Event.register("EVENT_SOUND_TIME_CHANGE")
    Event.EVENT_CHAT_CARD_TIME  = Event.register("EVENT_CHAT_CARD_TIME")

    Event.EVENT_FAMILY_ICON_CHANGE  = Event.register("EVENT_FAMILY_ICON_CHANGE")
    
    Event.EVENT_FREE_SOUND_TIME_CHANGE = Event.register("EVENT_FREE_SOUND_TIME_CHANGE")
    Event.EVENT_CHAT_POINT_CHANGE = Event.register("EVENT_CHAT_POINT_CHANGE")

    Event.EVENT_OPEN_PRIVATE_CHAT = Event.register("EVENT_OPEN_PRIVATE_CHAT")
    Event.EVENT_SET_IGNORE = Event.register("EVENT_SET_IGNORE")
    Event.EVENT_SET_CHAT_ALIGNMENT = Event.register("EVENT_SET_CHAT_ALIGNMENT")
    Event.EVENT_SET_CHAT_BAR_POS = Event.register("EVENT_SET_CHAT_BAR_POS")
    Event.EVENT_CHECK_IGNORE = Event.register("EVENT_CHECK_IGNORE")
    Event.EVENT_UPDATE_FRIEND_LIST_SHOW = Event.register("EVENT_UPDATE_FRIEND_LIST_SHOW")
    Event.EVENT_UPDATE_FRIEND_PRIVATE_SHOW = Event.register("EVENT_UPDATE_FRIEND_PRIVATE_SHOW")
    Event.EVENT_UPDATE_PRIVATE_HISTORY = Event.register("EVENT_UPDATE_PRIVATE_HISTORY")

    Event.EVENT_RECEIVE_PRIVATE_MSG = Event.register("EVENT_RECEIVE_PRIVATE_MSG")
    Event.EVENT_UPDATE_PRIVATE_RED_NUM = Event.register("EVENT_UPDATE_PRIVATE_RED_NUM")
    Event.EVENT_UPDATE_FRIEND_RED_NUM = Event.register("EVENT_UPDATE_FRIEND_RED_NUM")

    Event.EVENT_INVITE_GAME = Event.register("EVENT_INVITE_GAME")

    Event.EVENT_UPDATE_PLAYER_TAG_DATA = Event.register("EVENT_UPDATE_PLAYER_TAG_DATA")
    Event.EVENT_UPDATE_PLAYER_GAME_TIME = Event.register("EVENT_UPDATE_PLAYER_GAME_TIME")
    Event.EVENT_CHECK_ONE_IS_GAME_PLAYER = Event.register("EVENT_CHECK_ONE_IS_GAME_PLAYER")
    Event.EVENT_UPDATE_PLAYER_DETAIL_DATA = Event.register("EVENT_UPDATE_PLAYER_DETAIL_DATA")

    Event.EVENT_UPDATE_ONLINE_STATE_SHOW = Event.register("EVENT_UPDATE_ONLINE_STATE_SHOW")
    Event.EVENT_OPEN_PLAYER_INFORMATION = Event.register("EVENT_OPEN_PLAYER_INFORMATION")

    Event.EVENT_UPDATE_CHAT_NEAR_PLAYER = Event.register("EVENT_UPDATE_CHAT_NEAR_PLAYER")
else

end