---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/3/22 12:05
---

---@class WinEasterEggsTips : WinBase
local WinEasterEggsTips = M

function WinEasterEggsTips:init()
    WinBase.init(self, "EasterEggsTips.json")
    self:initUI()
    self:initEvent()
end

function WinEasterEggsTips:initUI()
    self.txtContent = self:child("EasterEggsTips-Content")
    self.imgContentBg = self:child("EasterEggsTips-BG")
end

--注册按钮点击事件，常驻事件监听也可在这里添加
function WinEasterEggsTips:initEvent()
    self:subscribe(self.imgContentBg, UIEvent.EventWindowClick, function()
        self:onHide()
    end)
end

--注册event事件监听，注意这里的事件是show的时候注册，close的时候注销的，常驻事件可在initEvent里面注册
function WinEasterEggsTips:subscribeEvent()
    --self._allEvent[#self._allEvent + 1] = Lib.subscribeEvent(Event.EVENT_EASTER_EGGS_TIPS, function(blockId, page, data)
    --end)
end

function WinEasterEggsTips:startCloseTimer()
    if self.closeTimer then
        return
    end

    self.closeTimer = World.Timer(20, function()
        self.waitCloseTime = self.waitCloseTime - 1
        if self.waitCloseTime <= 0 then
            self.closeTimer = nil
            self:onHide()
            return false
        end

        return true
    end)
end

--界面数据初始化
function WinEasterEggsTips:initView()
    self.txtContent:SetText(self.content)
    self.waitCloseTime = 2

    self:startCloseTimer()
end


function WinEasterEggsTips:onHide()
    UI:closeWnd("easterEggsTips")
end

function WinEasterEggsTips:onShow(isShow)
    if isShow then
        if not UI:isOpen(self) then
            UI:openWnd("easterEggsTips")
        else
            self:onHide()
        end
    else
        self:onHide()
    end
end

function WinEasterEggsTips:updateContent(content)
    self.content = content
    self:initView()
end

function WinEasterEggsTips:onOpen(content)
    self.content = content
    self:initView()
    self:subscribeEvent()
end

function WinEasterEggsTips:onClose()
    if self._allEvent then
        for k, fun in pairs(self._allEvent) do
            fun()
        end
        self._allEvent = {}
    end

    if self.closeTimer then
        self.closeTimer()
        self.closeTimer = nil
    end
end

return WinEasterEggsTips
