---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/12 17:36
---
---@class Component : cls
local Component = class("Component")

-----@param entity Entity

function Component:ctor(depends)
    self._depends = Lib.checktable(depends)
end

function Component:getDepends()
    return self._depends
end

function Component:getTarget()
    return self._target
end

function Component:_exportMethods(methods)
    self._exportMethods_ = methods
    local target = self._target
    local com = self
    for _, key in ipairs(methods) do
        if not target[key] then
            local m = com[key]
            target[key] = function(__, ...)
                return m(com, ...)
            end
        end
    end

    return self

end

function Component:bind(target)
    self._target = target
    for _, component in ipairs(self._depends) do
        if not target:checkComponent(component) then
            target:addComponent(component)
        end
    end

    self:onBind(target)
end

function Component:unbind()
    if self._exportMethods_ then
        local target = self._target
        for _, key in ipairs(self._exportMethods_) do
            target[key] = nil
        end
    end
    self:onUnbind()
end

function Component:onBind()

end

function Component:onUnbind()

end

function Component:serialize()

end

function Component:deserialize()

end


return Component