---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/5 14:38
---
local modules = {}

local function insertModule(moduleName, module)
    if modules[moduleName] then
        Lib.logInfo("module already exists", moduleName)
        return
    end
    modules[moduleName] = module
end

setmetatable(Engine, {
    __index = function(_, key)
        if modules[key] then
            return modules[key]
        end
        Lib.logError("module does not exist", key)
    end,
    __newindex = function()
        Lib.logError("Unable to assign value to Engine")
    end
})

return {
    insertModule = insertModule
}