---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/3/16 15:09
---

local ReportAttr = T(Config, "ReportAttr")

function ReportAttr.game_type(player)
    return "g2054"
end