---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/12 15:53
---
local easeCurve = class("EaseCurve")
local manager = require "core.manager"

function easeCurve:ctor(easeType)
    self.EaseType = Enum.EaseType[easeType] or Enum.EaseType.linear
end

function easeCurve:Evaluate(value)
    value = math.min(1, math.max(0, value))
    local target = 0
    local function getter()
        return target
    end
    local function setter(val)
        target = val
    end
    local tween = manager:createUnburdenedTween(getter, setter, 1, 1)
    tween:setEase(self.EaseType)
    tween._tweenBase:update(value)
    return target
end