---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/12 16:06
---
local propertyFunc = {}

propertyFunc["Instance"] = {
    get = function(tweenSet, ...)
        return tweenSet._ins
    end
}

propertyFunc["PlayStatus"] = {
    get = function(tweenSet)
        local status = Enum.TweenPlayStatus
        if not tweenSet._isPlay then
            return status.None
        end
        if tweenSet._isCancel then
            return status.Cancelled
        end
        local _, tween = next(tweenSet._tweens)
        if not tween then
            return status.None
        end
        if tween._tweenBase.status:isPaused() then
            return status.Paused
        end
        if tween._tweenBase.status:isDelaying() then
            return status.Delayed
        end
        if tween._tweenBase:isFinished() then
            return status.Completed
        end
        return status.Playing
    end
}

propertyFunc["TimeScale"] = {
    get = function(tweenSet)
        local _, tween = next(tweenSet._tweens)
        if not tween then
            return false
        end
        return tween._tweenBase.params.timeScale
    end,
    set = function(tweenSet, timeScale)
        timeScale = tonumber(timeScale)
        if not timeScale then
            return
        end
        for _, tween in pairs(tweenSet._tweens) do
            tween:setTimeScale(timeScale)
        end
    end
}

return propertyFunc