---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/12 15:46
---
---
---
require "extras.new.enum"
require "extras.new.tweenInfo"
require "extras.new.easeCurve"

class("Tween", require("extras.new.tweenSet"))