---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anybook.
--- DateTime: 2022/5/12 15:52
---

local tweenInfo = class("TweenInfo")

function tweenInfo:ctor(duration, easeCurve, playCount, playMode, delay)
    self.Duration = duration or 1
    self.EaseCurve = Lib.copy(easeCurve) or EaseCurve.new()
    self.PlayCount = playCount or 1
    self.PlayMode = Enum.TweenPlayMode[playMode] or Enum.TweenPlayMode.Positive
    self.Delay = delay or 0
end