---
--- Generated by PluginCreator
--- easter_eggs 's gate
--- DateTime:2022-03-15
--- @class EasterEggsClient
local EasterEggsClient = T(Lib, "EasterEggsClient")
--function EasterEggsClient:export_getXXX()
	-----TODO
--end

--function EasterEggsClient:import_getXXX()
	-----TODO
--end
return EasterEggsClient
