---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/18 16:09
---

local PriceGroups = {}
local LuckyLotteryPriceConfig = T(Config, "LuckyLotteryPriceConfig") ---@class LuckyLotteryPriceConfig

local function init()
    local config = Lib.read_csv_file(Root.Instance():getGamePath() .. "config/common/LuckyLotteryPrice.csv", 3) or {}
    for _, item in pairs(config) do
        local group = PriceGroups[tostring(item.groupId)] or {}
        local price = {
            id = tonumber(item.id),
            moneyType = tonumber(item.moneyType) or 0,
            moneyImage = item.moneyImage,
            price = tonumber(item.price) or 999,
            times = tonumber(item.times) or 1,
            priceLang = item.priceLang,
            discountPrice = tonumber(item.discountPrice) or 999,
            discountType = tonumber(item.discountType) or 0,
            discountCycle = tonumber(item.discountCycle) or 0
        }
        if price.moneyType == 1 then
            price.moneyType = 0
        end
        table.insert(group, price)
        PriceGroups[tostring(item.groupId)] = group
    end
    for _, group in pairs(PriceGroups) do
        table.sort(group, function(a, b)
            return a.times < b.times
        end)
    end
end

function LuckyLotteryPriceConfig:getPriceConfigByGroupId(groupId)
    return PriceGroups[tostring(groupId)]
end

function LuckyLotteryPriceConfig:getDisCountPrice(priceGroupId, type, discountCd)
    local priceConfigGroup = LuckyLotteryPriceConfig:getPriceConfigByGroupId(priceGroupId)
    local priceConfig = priceConfigGroup[type]
    local realPrice = priceConfig.price
    if discountCd ~= nil and priceConfig.discountPrice < priceConfig.price and discountCd <= 0 then
        realPrice = priceConfig.discountPrice
    end
    return realPrice
end

init()