---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2022/5/25 14:15
---
---@class UIImageset
local UIImageset = T(UILib, "UIImageset")

function UIImageset:format(imageset, name)
    return string.format("gameres|asset/imageset/%s:%s", imageset, name)
end

function UIImageset:moduleFormat(module, imageset, name)
    return string.format("gameres|asset/UI/%s/imageset/%s:%s", module, imageset, name)
end