---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2022/5/23 15:29
---
if World.isClient then
    require "client.ui_handler"
    require "client.ui_imageset"
end

local handlers = {}

return function(name, ...)
    if type(handlers[name]) ~= "function" then
        return
    end
    return handlers[name](...)
end