---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cs.
--- DateTime: 2019/4/9 11:04
---
local ShopBase = Shop.GetType("Base")
local MoneyShop = Shop.GetType("MoneyShop")

function MoneyShop:canBuy(packet)
    if not ShopBase.canBuy(self, packet, Me) then
        Lib.logDebug("money shop, can't buy")
        return false
    end
    Lib.logDebug("money shop can buy")
    return true
end