---
--- Generated by PluginCreator
--- easter_eggs handler
--- DateTime:2022-03-15
---
local handles = T(Player, "PackageHandlers")

--- @type EasterEggsMgr
local EasterEggsMgr = T(Lib, "EasterEggsMgr")

---@type EasterEggsRefreshPosConfig
local EasterEggsRefreshPosConfig = T(Config, "EasterEggsRefreshPosConfig")

---@type EasterEggsConfig
local EasterEggsConfig = T(Config, "EasterEggsConfig")

function handles:receiveEasterEggs(packet)
    local player = self
    local id = packet.id
    local mapName = packet.mapName
    local mapType = packet.mapType
    local eggId = packet.eggId

    Lib.logDebug("receiveEasterEggs ", packet)
    EasterEggsMgr:receiveEasterEggs(player, id, mapType)
end

function handles:requestRefreshEasterEggs(packet)
    return EasterEggsMgr:refreshEasterEggs(self, packet.refreshIndex)
end